### ISSUE TITLE
self hosted bot docs.md not found

### ISSUE THREAD

**Issue by 1Euro7Cent** [gregzaal/Auto-Voice-Channels#69]
when someone types vc/help the server get the response:

A FileNotFoundError error occured :(
Please ensure I have the correct permissions, check @AVC Premium help help for the correct command usage, and then try again. 
If that still doesn't help, try asking in the support server: https://discord.gg/qhMrz6u

and i am getting a private message with:

Server: 733421642910269480
FileNotFoundError with command help, params_str: ``
Traceback (most recent call last):
  File "/discordbot-AVC/Auto-Voice-Channels/commands/init.py", line 164, in run
    r = await cmd.execute(ctx, params)  # Run command
  File "/discordbot-AVC/Auto-Voice-Channels/commands/help_cmd.py", line 72, in execute
    with open("docs.md", 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'docs.md'

i already checked if the file/s are there and the file/s are there
i am hosting the bot on a private linux(ubuntu) server
and the bot have the permissions

**Comment by 1Euro7Cent** [comment]
And any dynamic templates don't work at all
