### ISSUE TITLE
roman.NotIntegerError: decimals can not be converted

### ISSUE THREAD

**Issue by notSalt** [gregzaal/Auto-Voice-Channels#84]
Bot is unable to properly name and create sessions
```Traceback (most recent call last):
  File "/home/salt/Auto-Voice-Channels/bot-env/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/salt/Auto-Voice-Channels/auto-voice-channels.py", line 248, in creation_loop
    await check_create(guild, settings)
  File "/home/salt/Auto-Voice-Channels/utils.py", line 41, in tmp
    return await func(*args, **kwargs)
  File "/home/salt/Auto-Voice-Channels/auto-voice-channels.py", line 236, in check_create
    await func.create_secondary(guild, p, u)
  File "/home/salt/Auto-Voice-Channels/utils.py", line 41, in tmp
    return await func(*args, **kwargs)
  File "/home/salt/Auto-Voice-Channels/functions.py", line 1240, in create_secondary
    name = await rename_channel(
  File "/home/salt/Auto-Voice-Channels/utils.py", line 41, in tmp
    return await func(*args, **kwargs)
  File "/home/salt/Auto-Voice-Channels/functions.py", line 810, in rename_channel
    cname = cname.replace('+#', roman.toRoman(i_str))
  File "/home/salt/Auto-Voice-Channels/bot-env/lib/python3.8/site-packages/roman.py", line 62, in toRoman
    raise NotIntegerError("decimals can not be converted")
roman.NotIntegerError: decimals can not be converted

**Comment by kywan** [comment]
#85 i patch it
